// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbE4NgLsIPyfavzkpbhWOVvXSteufSHtk',
    appId: '1:242650113610:web:4ec48f6aec56f75073e8b3',
    messagingSenderId: '242650113610',
    projectId: 'smartcartapp-dd0a7',
    authDomain: 'smartcartapp-dd0a7.firebaseapp.com',
    storageBucket: 'smartcartapp-dd0a7.firebasestorage.app',
    measurementId: 'G-6VDW3R0KHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBInI1DP6TuV5ryEjnzchIE7uqsMCqRm70',
    appId: '1:242650113610:android:9f0bd5891d87857573e8b3',
    messagingSenderId: '242650113610',
    projectId: 'smartcartapp-dd0a7',
    storageBucket: 'smartcartapp-dd0a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPygzy0-fmYhXpbrPS9Z4lTHvh2zQgd2E',
    appId: '1:242650113610:ios:acadd5fe891e0f6f73e8b3',
    messagingSenderId: '242650113610',
    projectId: 'smartcartapp-dd0a7',
    storageBucket: 'smartcartapp-dd0a7.firebasestorage.app',
    androidClientId: '242650113610-hrbj548tbp76f8615jfdqdfun8guu6hu.apps.googleusercontent.com',
    iosClientId: '242650113610-p6nlgfpvco3uq9d7kurti3f36afi01un.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlinegroceries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPygzy0-fmYhXpbrPS9Z4lTHvh2zQgd2E',
    appId: '1:242650113610:ios:acadd5fe891e0f6f73e8b3',
    messagingSenderId: '242650113610',
    projectId: 'smartcartapp-dd0a7',
    storageBucket: 'smartcartapp-dd0a7.firebasestorage.app',
    androidClientId: '242650113610-hrbj548tbp76f8615jfdqdfun8guu6hu.apps.googleusercontent.com',
    iosClientId: '242650113610-p6nlgfpvco3uq9d7kurti3f36afi01un.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlinegroceries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbE4NgLsIPyfavzkpbhWOVvXSteufSHtk',
    appId: '1:242650113610:web:1f695fe85897728a73e8b3',
    messagingSenderId: '242650113610',
    projectId: 'smartcartapp-dd0a7',
    authDomain: 'smartcartapp-dd0a7.firebaseapp.com',
    storageBucket: 'smartcartapp-dd0a7.firebasestorage.app',
    measurementId: 'G-ZKC3V6FH4N',
  );
}
