// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbE4NgLsIPyfavzkpbhWOVvXSteufSHtk',
    appId: '1:242650113610:web:19050a14c7da0e5f73e8b3',
    messagingSenderId: '242650113610',
    projectId: 'smartcartapp-dd0a7',
    authDomain: 'smartcartapp-dd0a7.firebaseapp.com',
    storageBucket: 'smartcartapp-dd0a7.firebasestorage.app',
    measurementId: 'G-01VGM7209H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBInI1DP6TuV5ryEjnzchIE7uqsMCqRm70',
    appId: '1:242650113610:android:d22452d6e930e06573e8b3',
    messagingSenderId: '242650113610',
    projectId: 'smartcartapp-dd0a7',
    storageBucket: 'smartcartapp-dd0a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPygzy0-fmYhXpbrPS9Z4lTHvh2zQgd2E',
    appId: '1:242650113610:ios:00b4e5f08deb550673e8b3',
    messagingSenderId: '242650113610',
    projectId: 'smartcartapp-dd0a7',
    storageBucket: 'smartcartapp-dd0a7.firebasestorage.app',
    androidClientId: '242650113610-hrbj548tbp76f8615jfdqdfun8guu6hu.apps.googleusercontent.com',
    iosClientId: '242650113610-miijmag7d2jebo4nk70lnpbc8o83t97o.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPygzy0-fmYhXpbrPS9Z4lTHvh2zQgd2E',
    appId: '1:242650113610:ios:00b4e5f08deb550673e8b3',
    messagingSenderId: '242650113610',
    projectId: 'smartcartapp-dd0a7',
    storageBucket: 'smartcartapp-dd0a7.firebasestorage.app',
    androidClientId: '242650113610-hrbj548tbp76f8615jfdqdfun8guu6hu.apps.googleusercontent.com',
    iosClientId: '242650113610-miijmag7d2jebo4nk70lnpbc8o83t97o.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbE4NgLsIPyfavzkpbhWOVvXSteufSHtk',
    appId: '1:242650113610:web:aa03330e3950b68573e8b3',
    messagingSenderId: '242650113610',
    projectId: 'smartcartapp-dd0a7',
    authDomain: 'smartcartapp-dd0a7.firebaseapp.com',
    storageBucket: 'smartcartapp-dd0a7.firebasestorage.app',
    measurementId: 'G-14JKWN8WFW',
  );
}
